parameters:
    flexsounds_ticket.user_load.class: Flexsounds\TicketBundle\EventListener\UserLoad
    flexsounds_ticket.twig_user.class: Flexsounds\TicketBundle\Extension\UserExtension
    flexsounds_ticket.ticket_manager.class: Flexsounds\TicketBundle\Entity\TicketManager

services:
    flexsounds_ticket.listener:
        class: %flexsounds_ticket.user_load.class%
        arguments: ['@service_container']
        tags:
            - { name: doctrine.event_listener, event: postLoad }

    flexsounds_ticket_user_extension:
        class: %flexsounds_ticket.twig_user.class%
        arguments: ['@service_container']
        tags:
            - { name: twig.extension }

    flexsounds_ticket.user:
        class: %hackzilla_ticket.user_bridge.class%
        arguments: ['@service_container']

    flexsounds_ticket.ticket_manager:
        class: %flexsounds_ticket.ticket_manager.class%
        arguments: ["@doctrine.orm.entity_manager"]