flexsounds_ticket:
    pattern:  /
    defaults: { _controller: "FlexsoundsTicketBundle:Ticket:index" }

flexsounds_ticket_show:
    pattern:  /{id}/show
    defaults: { _controller: "FlexsoundsTicketBundle:Ticket:show" }

flexsounds_ticket_new:
    pattern:  /new
    defaults: { _controller: "FlexsoundsTicketBundle:Ticket:new" }

flexsounds_ticket_create:
    pattern:  /create
    defaults: { _controller: "FlexsoundsTicketBundle:Ticket:create" }
    requirements: { _method: post }

flexsounds_ticket_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "FlexsoundsTicketBundle:Ticket:delete" }
    requirements: { _method: post|delete }

flexsounds_ticket_reply:
    pattern:  /{id}/reply
    defaults: { _controller: "FlexsoundsTicketBundle:Ticket:reply" }
